version: "3"

networks:
  laravel:
    driver: bridge

volumes:
     api-volume:
     frontend-volume:

services:
  #PHP Service
  api:
    build:
      context: ./laravel
      dockerfile: Dockerfile
      args:
        GIT_PERSONAL_ACCESS_TOKEN: ${GIT_PERSONAL_ACCESS_TOKEN}
    image: digitalocean.com/php
    container_name: api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
 
    working_dir: /var/www/shace/api
    volumes:
      - api-volume:/var/www/shace/api
      - ./laravel/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  

  # Nuxt Frontend
  frontend:
    build: 
      context: ./nuxtjs
      dockerfile: Dockerfile
      args:
        GIT_PERSONAL_ACCESS_TOKEN: ${GIT_PERSONAL_ACCESS_TOKEN}
        BASE_URL: http://localhost
        HOST: 0.0.0.0
        PORT: 4000
    container_name: frontend
    restart: always
    ports:
      - '4000:4000'
    volumes:
      - frontend-volume:/var/www/shace/frontend
    command: 'npm run start'
    depends_on:
      - api
    networks:
      - laravel

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - api-volume:/var/www/shace/api
      - frontend-volume:/var/www/shace/frontend
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf /etc/nginx/nginx.conf
    networks:
      - laravel
    depends_on:
      - api
      - frontend
  
